project:
  type: website
  output-dir: public

website:
  title: "goodrock"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: 
      light: lumen
      dark: darkly
    css: styles.css

editor: visual