[build]
command = 'quarto render'
publish = 'public'
[build.environment]

[context]
[context.branch-deploy]

[context.deploy-preview]

[context.production]
[context.production.environment]

[functions]
node_bundler = 'esbuild'

# THIS FIXES the no-cors issue
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"